# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
branches:
    only:
        - master

r_github_packages:
    - r-lib/devtools
    - r-lib/pkgdown

before_script:
    - Rscript -e 'devtools::document()'

script:
    - Rscript -e 'pkgdown::build_site()'

deploy:
    verbose: true
    provider: pages
    skip_cleanup: true
    on:
        branch: master
    local_dir: docs
    target_branch: master
    edge:
        branch: pages-ivar-set
