# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libxml2-dev
      - libv8-3.14-dev

r:
- 3.3
- 3.4
- 3.5
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'
